---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smarttuning-sampler-config
  namespace: teastore
data:
  # ((((memory / (2**20)) * 0.013375) + (cpu * 0.0535) ) / 2)
  # "penalization": "(1-errors)*(1/(1+process_time))*(memory_limit/(memory_limit + abs(xmx-memory_limit)))",
  #"objective": "-(penalization)*(throughput/(((memory_limit * 0.013375) + (cpu_limit * 0.0535) ) / 2))",
  # "objective": "-(penalization)*(1/(1+process_time))*((throughput)/((memory_limit/(2**10) + cpu_limit)))",
  # "objective": "-(penalization)*(1/(1+(throughput/(1/process_time))))*(1/((memory_limit/(2**10) + cpu_limit)))",
  #"objective": "-(penalization)*(1/(1+process_time))*(throughput/((memory_limit/(2**10) + cpu_limit)))",

  sampler.json: |
    {
      "objective": "-(penalization)*(throughput/((memory_limit/(2**10) + cpu_limit))) * 1/(1+process_time)",
      "penalization": "1/(1+(errors/throughput))",
      "metrics": [
        {
          "name": "cpu",
          "query": "f'sum(rate(container_cpu_usage_seconds_total{{id=~\".*kubepods.*\",pod=~\"{podname}-.*\",name!~\".*POD.*\",namespace=\"{namespace}\",container=\"\"}}[{interval}s]))'",
          "datasource": "prom"
        },
        {
          "name": "cpu_limit",
          "query": "f'sum(sum_over_time(container_spec_cpu_quota{{id=~\".*kubepods.*\",pod=~\"{podname}-.*\",name!~\".*POD.*\",namespace=\"{namespace}\",container=\"\"}}[{interval}s])) / avg(sum_over_time(container_spec_cpu_period{{id=~\".*kubepods.*\",pod=~\"{podname}-.*\",name!~\".*POD.*\",namespace=\"{namespace}\",container=\"\"}}[{interval}s]))'",
          "datasource": "prom"
        },
        {
          "name": "memory",
          "query": "f'sum(max_over_time(container_memory_working_set_bytes{{id=~\".*kubepods.*\",pod=~\"{podname}-.*\",name!~\".*POD.*\",namespace=\"{namespace}\",container=\"\"}}[{interval}s]))/(2^20)'",
          "datasource": "prom"
        },
        {
          "name": "memory_limit",
          "query": "f'sum(max_over_time(container_spec_memory_limit_bytes{{id=~\".*kubepods.*\",pod=~\"{podname}-.*\",name!~\".*POD.*\",namespace=\"{namespace}\",container=\"\"}}[{interval}s]))/(2^20)'",
          "datasource": "prom"
        },
        {
          "name": "errors",
          "query": "f'sum(rate(smarttuning_http_requests_total{{pod=~\"{podname}-.*\", code=~\"5..\",name!~\".*POD.*\"}}[{interval}s]))'",
          "datasource": "prom"
        },
        {
          "name": "throughput",
          "query": "f'sum(rate(smarttuning_http_requests_total{{pod=~\"{podname}-.*\",name!~\".*POD.*\"}}[{interval}s]))'",
          "datasource": "prom"
        },
        {
          "name": "process_time",
          "query":"f'avg(rate(smarttuning_http_processtime_seconds_sum{{pod=~\"{podname}-.*\",name!~\".*POD.*\"}}[{interval}s])) / sum( rate(smarttuning_http_processtime_seconds_count{{pod=~\"{podname}-.*\",name!~\".*POD.*\"}}[{interval}s]))'",
          "datasource": "prom"
        }
      ]
    }
---
