apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader-db
  labels:
    app: daytrader-db
spec:
  replicas: 1
  template:
    metadata:
      name: daytrader-db
      labels:
        app: daytrader-db
    spec:
      containers:
        - name: daytrader-db
          image: smarttuning/derby
          ports:
            - containerPort: 1527
              protocol: TCP
      restartPolicy: Always
  selector:
    matchLabels:
      app: daytrader-db