# make it reacheable by prometheus
apiVersion: v1
kind: Service
metadata:
  name: daytrader
  annotations:
    injection.smarttuning.ibm.com: "true"
  labels:
    app: daytrader
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 493
      name: https
    - nodePort: 30088
      port: 9080
      targetPort: 9080
      name: http
  selector:
    app: daytrader
  # export KUBE_TOKEN=$(</var/run/secrets/kubernetes.io/serviceaccount/token)
  # curl -sSk -H "Authorization: Bearer $(</var/run/secrets/kubernetes.io/serviceaccount/token)" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/
---
#### Daytrader Database  #####
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: daytrader-db
  name: daytrader-db
spec:
  ports:
    - name: "1527"
      port: 1527
      protocol: TCP
      targetPort: 1527
  selector:
    app: daytrader-db
status:
  loadBalancer: {}
