apiVersion: v1
kind: ConfigMap
metadata:
  name: daytrader-config-app
data:
  # default 100
  HTTP_MAX_KEEP_ALIVE_REQUESTS: "100"
  # default 30
  HTTP_PERSIST_TIMEOUT: "30"
  # default 60
  HTTP_READ_TIMEOUT: "60"
  # default 60
  HTTP_WRITE_TIMEOUT: "60"
  ## Connection Pools
  # JDBC Trade Source
  # default 30
#  CONMGR1_TIMEOUT: "210"
  CONMGR1_TIMEOUT: "30"
  # default -1
#  CONMGR1_AGED_TIMEOUT: "20"
  CONMGR1_AGED_TIMEOUT: "-1"
  # default 1800
#  CONMGR1_MAX_IDLE_TIMEOUT: "210"
  CONMGR1_MAX_IDLE_TIMEOUT: "1800"
  # default 180
#  CONMGR1_REAP_TIME: "84"
  CONMGR1_REAP_TIME: "180"
  # default 50
#  CONMGR1_MAX_POOL_SIZE: "100"
  CONMGR1_MAX_POOL_SIZE: "50"
  # default 0
#  CONMGR1_MIN_POOL_SIZE: "50"
  CONMGR1_MIN_POOL_SIZE: "0"
  CONMGR1_PURGE_POLICY: "FailingConnectionOnly"
  CONMGR1_CONN_PER_THREAD: "1"
  # Trade Broker QCF
  CONMGR3_TIMEOUT: "0"
  CONMGR3_AGED_TIMEOUT: "0"
  CONMGR3_MAX_IDLE_TIMEOUT: "1"
  CONMGR3_REAP_TIME: "1"
  CONMGR3_MAX_POOL_SIZE: "200"
  CONMGR3_MIN_POOL_SIZE: "4"
  CONMGR3_PURGE_POLICY: "FailingConnectionOnly"
  CONMGR3_CONN_PER_THREAD: "1"
  # Trader Streamer TCF
#  CONMGR4_TIMEOUT: "0"
#  CONMGR4_AGED_TIMEOUT: "0"
#  CONMGR4_MAX_IDLE_TIMEOUT: "0"
#  CONMGR4_REAP_TIME: "120"
#  CONMGR4_MAX_POOL_SIZE: "200"
#  CONMGR4_MIN_POOL_SIZE: "4"
#  CONMGR4_PURGE_POLICY: "FailingConnectionOnly"
#  CONMGR4_CONN_PER_THREAD: "1"
  ## Thread Pool
  # default 0
#  CORE_THREADS: "4"
  CORE_THREADS: "0"
  # default -1
#  MAX_THREADS: "99"
  MAX_THREADS: "-1"
  ## App
  # SYNC:0, ASYNC:1, ASYNC_2P:0
  ORDER_PROCESSING_MODE: "0"
  # FULL_EJB:0, DIRECT:1, SESSION:2
  RUNTIME_MODE: "1"
  # JSP: 0, JSP-IMG: 1
  WEB_INTERFACE: "0"
