apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader-service
  annotations:
    injection.smarttuning.ibm.com: "true"
spec:
  selector:
    matchLabels:
      app: daytrader
  replicas: 1
  template:
    metadata:
      labels:
        app: daytrader
    spec:
      containers:
        - name: daytrader
          image: smarttuning/daytrader8-k8s
          resources:
            limits:
              cpu: "2"
              memory: "4096Mi"
          ports:
            - containerPort: 9080
          env:
            - name: DB_ADDRESS
              value: daytrader-db.default.svc.cluster.local
            - name: DB_PORT
              value: "1527"
            - name: MAX_QUOTES
              value: "1000"
            - name: MAX_USERS
              value: "500"
          livenessProbe:
            httpGet:
              path: /health
              port: "http"
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: daytrader-config-app
          volumeMounts:
            - mountPath: /etc/daytrader-config-app
              name: daytrader-config-app
            - mountPath: /config/jvm.options
              subPath: jvm.options
              name: daytrader-config-jvm
      volumes:
        - name: daytrader-config-app
          configMap:
            name: daytrader-config-app
        - name: daytrader-config-jvm
          configMap:
            name: daytrader-config-jvm
