{
 "title": "smarttuning",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "remap_http_requests_total" },
   {
    "name": "time_interval_m",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "prod_podname",
    "query": "container_cpu_usage_seconds_total"
   },
   {
    "name": "train_podname",
    "query": "container_cpu_usage_seconds_total"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput / MB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / (sum( sum_over_time(container_memory_working_set_bytes{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / 1024 / 1024)",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / (sum( sum_over_time(container_memory_working_set_bytes{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / 1024 / 1024)",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  },
  {
   "title": "Process Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /sum( rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /sum( rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  }
 ]
}