{
 "title": "Daytrader Vendor Metrics Copy",
 "time": { "from": "2021-06-29T00:18:18.000Z", "to": "now" },
 "panels": [
  {
   "title": "JVM GC / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_total[1m])) by (name) / sum(deriv(base_gc_time_seconds[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM GC total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_total[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Conn pool waiting time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(deriv(vendor_connectionpool_waitTime_total_seconds{pod=~\"daytrader-service-.*\",name!~\".*POD.*\"}[1m])) by( datasource) /avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"daytrader-service-.*\",name!~\".*POD.*\"}[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Queued connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"daytrader-service-.*\",name!~\".*POD.*\"}[1m])) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(vendor_threadpool_activeThreads{pod=~\"daytrader-service-.*\",name!~\".*POD.*\"}[1m]))",
     "legendFormat": "thread pool"
    },
    {
     "expr": "avg(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"daytrader-service-.*\",name!~\".*POD.*\"}[1m])) by (datasource)",
     "legendFormat": "conn pool -- {{datasource}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"daytrader-service-.*\",name!~\".*POD.*\",namespace=\"default\",container=\"\"}[1m])) / avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"daytrader-service-.*\",name!~\".*POD.*\",namespace=\"default\",container=\"\"}[1m]))\n",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"daytrader-service-.*\",name!~\".*POD.*\",container=\"\"}[1m]))  by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(deriv(vendor_servlet_responseTime_total_seconds{pod=~\"daytrader-service-.*\",servlet!~\"com_ibm_ws_microprofile.*\"}[1m])) ",
     "legendFormat": "total"
    },
    {
     "expr": "avg(deriv(vendor_servlet_responseTime_total_seconds{pod=~\"daytrader-service-.*\",servlet!~\"com_ibm_ws_microprofile.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vendor_servlet_request_total{pod=~\"daytrader-service-.*\",servlet!~\"com_ibm_ws_microprofile.*\"}[1m])) > 0",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(vendor_servlet_request_total{pod=~\"daytrader-service-.*\",servlet!~\"com_ibm_ws_microprofile.*\"}[1m])) by (pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(base_memory_maxHeap_bytes{pod=~\"daytrader-service-.*\"}[1m]))",
     "legendFormat": "heap total"
    },
    {
     "expr": "sum(avg_over_time(base_memory_usedHeap_bytes{pod=~\"daytrader-service-.*\"}[1m])) by (pod)",
     "legendFormat": "heap usage {{pod}} "
    },
    {
     "expr": "sum(avg_over_time(base_memory_committedHeap_bytes{pod=~\"daytrader-service-.*\"}[1m])) by (pod)",
     "legendFormat": "commited {{pod}}"
    }
   ]
  },
  {
   "title": "heap usage / commited",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(base_memory_usedHeap_bytes{pod=~\"daytrader-service-.*\"}[1m])) by (pod) / sum(avg_over_time(base_memory_committedHeap_bytes{pod=~\"daytrader-service-.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "heap / physical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(base_memory_usedHeap_bytes{pod=~\"daytrader-service-.*\"}[1m])) by (pod) / sum(avg_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"daytrader-service-.*\",name!~\".*POD.*\", container=\"\"}[1m])) by (pod)",
     "legendFormat": "mem usage {{pod}}"
    }
   ]
  },
  {
   "title": "physical memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"daytrader-service-.*\",name!~\".*POD.*\", container=\"\"}[1m])) ",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(avg_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"daytrader-service-.*\",name!~\".*POD.*\", container=\"\"}[1m])) by (pod)",
     "legendFormat": "mem usage {{pod}}"
    }
   ]
  }
 ]
}