{
 "title": "smarttuning-replicas",
 "time": { "from": "2021-05-28T06:06:43.000Z", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "container_cpu_usage_seconds_total"
   },
   {
    "name": "time_interval_m",
    "query": "30s,1m,100s,200s,5m,6m,400s,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "prod_podname",
    "query": "container_cpu_usage_seconds_total"
   },
   {
    "name": "train_podname",
    "query": "container_cpu_usage_seconds_total"
   }
  ]
 },
 "panels": [
  { "title": "vendor metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queued Requests Connection Pool",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$train_podname-.*\", name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    },
    {
     "expr": "avg(deriv(vendor_agroal_awaiting_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "avg(deriv(vendor_agroal_awaiting_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "avg(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    },
    {
     "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    }
   ]
  },
  {
   "title": "Connection Pool Waiting Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(deriv(vendor_connectionpool_waitTime_total_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) /avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "avg(deriv(vendor_connectionpool_waitTime_total_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) / avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
     "legendFormat": "TRAIN {{datasource}}"
    },
    {
     "expr": "avg(deriv(vendor_agroal_blocking_time_average_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) ",
     "legendFormat": "PROD {{datasource}}"
    },
    {
     "expr": "avg(deriv(vendor_agroal_blocking_time_average_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) ",
     "legendFormat": "TRAIN {{datasource}}"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(vendor_threadpool_activeThreads{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD thread pool"
    },
    {
     "expr": "avg(avg_over_time(vendor_threadpool_activeThreads{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN thread pool"
    },
    {
     "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD thread pool"
    },
    {
     "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN thread pool"
    }
   ]
  },
  { "title": "smarttuning metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "# replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$prod_podname\"}[$time_interval_m])",
     "legendFormat": "PROD"
    },
    {
     "expr": "avg_over_time(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$train_podname\"}[$time_interval_m])",
     "legendFormat": "TRAIN"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(vendor_servlet_request_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "sPROD $prod_podname"
    },
    {
     "expr": "sum(rate(vendor_servlet_request_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "sTRAIN $train_podname"
    }
   ]
  },
  {
   "title": "objective -- [1/(1+resp time)] * [throughput /(n * cost)]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1-sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))) *\n  (\n      1 / (1+ (sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))))\n  ) *\n  sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /\n  (\n    (\n      (\n((0.0535*sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        (0.013375*(sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^20)) /2\n    ) \n  )\n) \n \n",
     "legendFormat": "[SUM] PROD $prod_podname"
    },
    {
     "expr": "(1-sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))) *\n  (\n      1 / (1+ (sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_processtime_seconds_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))))\n  ) *\n  sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /\n  (\n    (\n      (\n((0.0535*sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        (0.013375*(sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^20)) /2\n    ) \n  )\n) \n \n",
     "legendFormat": "[TRAIN-SUM] $train_podname"
    },
    {
     "expr": "(1-sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))) *\n  (\n      1 / (1+ (sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))))\n  ) *\n  sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /\n  ((sum(count(count(sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container!=\"\"}[$time_interval_m])) by (container,pod)) by (pod) > 1) by (pod)) )*\n    (\n      (\n((0.0535*sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        (0.013375*(sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^20)) /2\n    ) \n  )\n) \n \n",
     "legendFormat": "[REP] PROD $prod_podname"
    },
    {
     "expr": "(1-sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))) *\n  (\n      1 / (1+ (sum(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum(rate(smarttuning_http_processtime_seconds_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))))\n  ) *\n  sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) /\n  ((sum(count(count(sum(rate(container_cpu_usage_seconds_total{id=~\".kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container!=\"\"}[$time_interval_m])) by (container,pod)) by (pod) > 1) by (pod)) )*\n    (\n      (\n((0.0535*sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        (0.013375*(sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^20)) /2\n    ) \n  )\n) \n \n",
     "legendFormat": "[TRAIN-REP] $train_podname"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "avg(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "avg(deriv(vendor_servlet_responseTime_total_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "sPROD $prod_podname"
    },
    {
     "expr": "avg(deriv(vendor_servlet_responseTime_total_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "sTRAIN $train_podname"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))",
     "legendFormat": "prod + train"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\".*-db-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))",
     "legendFormat": "database"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"smarttuning-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))",
     "legendFormat": "smarttuning"
    }
   ]
  },
  {
   "title": "Memory - container size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) \n",
     "legendFormat": "PROD"
    },
    {
     "expr": "sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "TRAIN"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])) \n",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])) ",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"$prod_podname.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "prod + train"
    },
    {
     "expr": "\nsum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) / avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=~\"\"}[$time_interval_m]))\n",
     "legendFormat": "limit $prod_podname"
    },
    {
     "expr": "\nsum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) / avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))\n",
     "legendFormat": "limit $train_podname"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  }
 ]
}