{
 "title": "smarttuning-replicas",
 "time": { "from": "2021-06-23T20:56:25.000Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   },
   {
    "name": "time_interval_m",
    "query": "30s,1m,100s,200s,5m,6m,400s,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "prod_podname",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   },
   {
    "name": "train_podname",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   }
  ]
 },
 "panels": [
  { "title": "Smart Tuning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prod Config",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(smarttuning_knob_value{app=\"$prod_podname\"}[1m])) by (knob)",
     "legendFormat": "{{knob}}"
    }
   ]
  },
  {
   "title": "Train Config",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(smarttuning_knob_value{app=\"$train_podname\"}[1m])) by (knob)",
     "legendFormat": "{{knob}}"
    }
   ]
  },
  {
   "title": "vendor metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queued Requests Connection Pool",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "PROD {{datasource}}"
      },
      {
       "expr": "avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$train_podname-.*\", name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "TRAIN {{datasource}}"
      },
      {
       "expr": "avg(deriv(vendor_agroal_awaiting_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "PROD {{datasource}}"
      },
      {
       "expr": "avg(deriv(vendor_agroal_awaiting_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "TRAIN {{datasource}}"
      }
     ]
    },
    {
     "title": "Connection Pool",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "PROD {{datasource}}"
      },
      {
       "expr": "avg(avg_over_time(vendor_connectionpool_managedConnections{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "TRAIN {{datasource}}"
      },
      {
       "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "PROD {{datasource}}"
      },
      {
       "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "TRAIN {{datasource}}"
      }
     ]
    },
    {
     "title": "Connection Pool Waiting Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(deriv(vendor_connectionpool_waitTime_total_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) /avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "PROD {{datasource}}"
      },
      {
       "expr": "avg(deriv(vendor_connectionpool_waitTime_total_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) / avg(rate(vendor_connectionpool_queuedRequests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by (datasource)",
       "legendFormat": "TRAIN {{datasource}}"
      },
      {
       "expr": "avg(deriv(vendor_agroal_blocking_time_average_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) ",
       "legendFormat": "PROD {{datasource}}"
      },
      {
       "expr": "avg(deriv(vendor_agroal_blocking_time_average_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) by( datasource) ",
       "legendFormat": "TRAIN {{datasource}}"
      }
     ]
    },
    {
     "title": "Thread pool",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(vendor_threadpool_activeThreads{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
       "legendFormat": "PROD thread pool"
      },
      {
       "expr": "avg(avg_over_time(vendor_threadpool_activeThreads{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
       "legendFormat": "TRAIN thread pool"
      },
      {
       "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
       "legendFormat": "PROD thread pool"
      },
      {
       "expr": "avg(avg_over_time(vendor_agroal_active_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
       "legendFormat": "TRAIN thread pool"
      }
     ]
    }
   ]
  },
  { "title": "smarttuning metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "# replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$prod_podname\"}[$time_interval_m])",
     "legendFormat": "PROD"
    },
    {
     "expr": "avg_over_time(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$train_podname\"}[$time_interval_m])",
     "legendFormat": "TRAIN"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "smarttuning_metric{metric=\"throughput\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"throughput\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  },
  {
   "title": "objective ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "-1*smarttuning_metric{metric=\"objective\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "-1*smarttuning_metric{metric=\"objective\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  },
  {
   "title": "Penalization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-smarttuning_metric{metric=\"penalization\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "1-smarttuning_metric{metric=\"penalization\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "smarttuning_metric{metric=\"process_time\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"process_time\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "smarttuning_metric{metric=\"errors\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"errors\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  },
  {
   "title": "Memory ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "smarttuning_metric{metric=\"memory_limit\", app=\"$prod_podname\"}\n",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"memory_limit\", app=\"$train_podname\"}\n",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"memory\", app=\"$prod_podname\"}\n",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"memory\", app=\"$train_podname\"}\n",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smarttuning_metric{metric=\"cpu_limit\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"cpu_limit\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"cpu\", app=\"$prod_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    },
    {
     "expr": "smarttuning_metric{metric=\"cpu\", app=\"$train_podname\"}",
     "legendFormat": "{{app}} -- {{metric}}"
    }
   ]
  }
 ]
}