apiVersion: "smarttuning.ibm.com/v1alpha2"
kind: SearchSpace
metadata:
  name: acmeair-ss
  namespace: acmeair
spec:
  deployment: acmeair-service
  service: acmeair-svc
  namespace: "acmeair"
  manifests:
    - name: acmeair-service
      type: "deployment"
    - name: acmeair-config-app
      type: "configMap"
    - name: acmeair-config-jvm
      type: "configMap"
data:
  - name: acmeair-service
    tunables:
      option:
        - name: "cpu"
          type: "integer"
          values:
            - "1"
        - name: "memory"
          type: "integer"
          values:
            - "512"
            - "1024"
            - "1536"
            - "2048"
            - "2560"
            - "4096"
  - name: acmeair-config-app
    tunables:
      number:
        - name: "HTTP_MAX_KEEP_ALIVE_REQUESTS"
          lower:
            value: 10
          upper:
            value: 200
          step: 25
          real: False
        - name: "HTTP_PERSIST_TIMEOUT"
          lower:
            value: 15
          upper:
            value: 45
          step: 5
          real: False
        - name: "MONGO_MAX_CONNECTIONS"
          lower:
            value: 10
          upper:
            value: 200
          step: 25
          real: False
        - name: "EXECUTOR_MAX_THREADS"
          lower:
            value: 1
          upper:
            value: 300
          step: 10
  - name: acmeair-config-jvm
    filename: "jvm.options"
    tunables:
       number:
        - name: "-Xms"
          lower:
            value: 8
          upper:
            value: 8192
            dependsOn: "-Xmx"
          step: 8
          real: False
        - name: "-Xmx"
          lower:
            value: 16
          upper:
            value: 8192
            dependsOn: "memory 0.50 *"
          step: 16
          real: False
        - name: "-Xmns"
          lower:
            value: 8
          upper:
            value: 8192
            dependsOn: "-Xms 0.8 *"
          step: 32
          real: False
        - name: "-Xmnx"
          lower:
            value: 8
            dependsOn: "-Xmns"
          upper:
            value: 8192
            dependsOn: "-Xmx 0.8 *"
          step: 32
          real: False
        - name: "-Xscmx"
          lower:
            value: 16
          upper:
            value: 512
            dependsOn: "-XX:SharedCacheHardLimit"
          step: 16
          real: False
        - name: "-XX:SharedCacheHardLimit"
          lower:
            value: 16
          upper:
            value: 512
          step: 16
          real: False
       boolean:
        - name: "-Xtune:virtualized"
       option:
        - name: "container_support"
          values:
            - "-XX:+UseContainerSupport"
        - name: "gc"
          values:
            - "-Xgcpolicy:gencon"
            - "-Xgcpolicy:concurrentScavenge"
            - "-Xgcpolicy:metronome"
            - "-Xgcpolicy:optavgpause"
            - "-Xgcpolicy:optthruput"
