kind: Namespace
apiVersion: v1
metadata:
  name: kube-tuning
  labels:
    name: kube-tuning
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-tuning
  name: kube-tuning-sampler-configmap
data:
  HIST_QUERY: ''
  URL_LABELS: ''
  MEAN_QUERY: 'avg_over_time(machine_cpu_cores[60s]),avg_over_time(machine_memory_bytes[60s])'
  STD_QUERY: 'stddev_over_time(machine_cpu_cores[60s]),stddev_over_time(machine_memory_bytes[60s])'
  APPLICATION: 'acmeair'
  METRIC: 'cpu,memory'
  PROMETHEUS_ENDPOINT: 'prometheus-service.kube-monitoring.svc.cluster.local'
  PROMETHEUS_PORT: '9090'
  QUERY_STEP: '5'
  MONGO_ENDPOINT: 'localhost'
  MONGO_PORT: '27017'
  MONGO_DB: 'acmeair_db_experiments'
  MONGO_COLLECTION: 'acmeair_metrics'
  MONGO: 'None'
  KEEP_DATA: 'false'
  BUFFER: '0'
  SCRAP_INTERVAL: '5'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-tuning
  name: kube-tuning-sampler
spec:
  # https://blog.container-solutions.com/kube-deployment-strategies
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: kube-tuning-sampler
  template:
    metadata:
      labels:
        app: kube-tuning-sampler
    spec:
      containers:
      - name: kube-tuning-sampler
        image: tuning/sampling:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        envFrom:
          - configMapRef:
              name: kube-tuning-sampler-configmap

