apiVersion: v1
kind: ConfigMap
metadata:
  name: acmeair-config-app
data:
  MONGO_HOST: acmeair-db.default.svc.cluster.local
  MONGO_PORT: "27017"
  MONGO_DBNAME: acmeair
  SERVER_PORT: "9080"
  USE_FLIGHT_DATA_RELATED_CACHING: "false"
  LOG_DIR: "/logs"
  WLP_LOGGING_CONSOLE_FORMAT: "basic"
  WLP_LOGGING_CONSOLE_LOGLEVEL: "info"
  # default max connectionPoolSize MONGO_MAX_CONNECTIONS=100
  MONGO_MAX_CONNECTIONS: "100"
  # default 10
  MONGO_MIN_CONNECTIONS: "1"
  # default 10
  MONGO_CONNECTION_TIMEOUT: "10"
  # Openliberty specific
  # default 100
  HTTP_MAX_KEEP_ALIVE_REQUESTS: "100"
  # default 30
  HTTP_PERSIST_TIMEOUT: "30"
  # default 60
  HTTP_READ_TIMEOUT: "60"
  # default 60
  HTTP_WRITE_TIMEOUT: "60"
  # default -1
  EXECUTOR_CORE_THREADS: "-1"
  # default -1
  EXECUTOR_MAX_THREADS: "-1"
  # default 60
  EXECUTOR_KEEP_ALIVE: "60"
  # default LOCAL, other STRIC NEVER
  EXECUTOR_STEAL_POLICY: "LOCAL"
  # default ABORT, other CALLER_RUNS
  EXECUTOR_REJECTED_WORK_POLICY: "CALLER_RUNS"
---
