apiVersion: v1
kind: ConfigMap
metadata:
  name: acmeair-config-jvm
data:
  # cannot set empty jvm.options
  # if it is candidate to be tuned, i.e., they are set on the search space
  # put here the default values of these knobs
  jvm.options: |-
    -XX:+UseContainerSupport
    -Xgcpolicy:gencon
---
