apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-dep
  labels:
    app: "acmeair"
  annotations:
    injection.smarttuning.ibm.com: "true"
spec:
  replicas: 1
  template:
    metadata:
      name: acmeair
      labels:
        app: "acmeair"
    spec:
      containers:
        - name: acmeair
          image: smarttuning/liberty-acmeair-k8s
          resources:
            limits:
              cpu: "2"
              memory: "4096Mi"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 9080
              path: /acmeair-webapp/
            initialDelaySeconds: 60
            failureThreshold: 2
            periodSeconds: 10
          ports:
            - containerPort: 9080
          envFrom:
            - configMapRef:
                name: acmeair-config-app
          volumeMounts:
            - mountPath: /etc/acmeair-config-app
              name: acmeair-config-app
            - mountPath: /config/jvm.options
              subPath: jvm.options
              name: acmeair-config-jvm
      volumes:
        - name: acmeair-config-app
          configMap:
            name: acmeair-config-app
        - name: acmeair-config-jvm
          configMap:
            name: acmeair-config-jvm
  selector:
    matchLabels:
      app: acmeair
