---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-svc
  annotations:
    injection.smarttuning.ibm.com: "true"
  labels:
    app: acmeair
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 493
      name: https
    - nodePort: 30088
      port: 9080
      targetPort: 9080
      name: http
  selector:
    app: "acmeair"
---
