---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-svc
  namespace: quarkus
  labels:
    app: quarkus-svc
  annotations:
    injection.smarttuning.ibm.com: "true"
spec:
  ports:
  - port: 9080
    targetPort: 9080
    name: http
  selector:
    app: quarkus-service
    smarttuning: "false"
  type: NodePort
---
