apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-config
data:
  JLOAD_BOOKINGS: 'false'
  # total users id
  JUSERS: '5'
  # max value user id
  JUSER: '4'
  JTHREAD: '10'
  JDURATION: '60'
  JURL: 'acmeair-webapp'
  JPORT: '8888'
  JMIN_SESSION_DURATION: '0'
  JMAX_SESSION_DURATION: '60'
  JMIN_THINK: '0'
  JMAX_THINK: '0'
  JREPEAT: '1'
  JRAMPUP: '10'
  THREAD_GROUP: 'workload-uniform'
  #  THREAD_GROUP: 'workload-uniformconst'
  #  JTARGET_THROUGHPUT: '360000'
  TEST_PLAN: 'tuning-workloads.jmx'
