apiVersion: v1
kind: Pod
metadata:
  name: jmeter
  labels:
    app: jmeter
spec:
  containers:
    - name: jmeter
      image: jmeter_acmeair
      lifecycle:
        preStop:
          exec:
            command:
              - "sh"
              - "-c"
              - |
                shutdown.sh
      imagePullPolicy: Never
      env:
        - name: LIBERTYHOST
          value: 'acmeair.default.svc.cluster.local'
      envFrom:
        - configMapRef:
            name: jmeter-config
      volumeMounts:
        - mountPath: /etc/jmeter
          name: jmeter-config
        - mountPath: /output
          name: jmeter-output
  terminationGracePeriodSeconds: 5
  volumes:
    - name: jmeter-config
      configMap:
        name: jmeter-config
    - name: jmeter-output
      hostPath:
        path: /smarttuning/jmeter/prod
  restartPolicy: Never



