apiVersion: "smarttuning.ibm.com/v1alpha2"
kind: SearchSpace
metadata:
  name: daytrader-ss
  namespace: daytrader
spec:
  deployment: daytrader-service
  service: daytrader
  namespace: "daytrader"
  manifests:
    - name: daytrader-service
      type: "deployment"
    - name: daytrader-config-app
      type: "configMap"
    - name: daytrader-config-jvm
      type: "configMap"
data:
  - name: daytrader-service
    tunables:
      option:
        - name: "cpu"
          type: "real"
          values:
            - "2"
        - name: "memory"
          type: "integer"
          values:
            - "1024"
            - "1536"
            - "2048"
            - "2560"
            - "4096"
  - name: daytrader-config-app
    # https://www.ibm.com/support/pages/tuning-connection-pool-properties-websphere-application-server
    # https://openliberty.io/docs/20.0.0.9/reference/config/connectionManager.html
    # https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_tun.html
    tunables:
      number:
        - name: "MAX_THREADS"
          lower:
            value: 10
          upper:
            dependsOn: "CONMGR1_MAX_POOL_SIZE"
            value: 100
          step: 1
          real: False
        # JDBC Conn Pool
        - name: "CONMGR1_MAX_POOL_SIZE"
          lower:
            value: 10
          upper:
            value: 100
          step: 1
          real: False
        - name: "CONMGR1_MIN_POOL_SIZE"
          lower:
            value: 4
          upper:
            value: 100
            dependsOn: "CONMGR1_MAX_POOL_SIZE"
          step: 1
          real: False
        - name: "CONMGR1_TIMEOUT"
          lower:
            value: 1
          upper:
            value: 300
          step: 10
          real: False
        - name: "CONMGR1_AGED_TIMEOUT"
          lower:
            value: 1
          upper:
            value: 300
          step: 10
          real: False
        - name: "CONMGR1_MAX_IDLE_TIMEOUT"
          lower:
            value: 1
          upper:
            value: 300
          step: 30
          real: False
        - name: "CONMGR1_REAP_TIME"
          lower:
            value: 1
          upper:
            value: 300
            dependsOn: "CONMGR1_MAX_IDLE_TIMEOUT"
          step: 30
          real: False
        # TCF Conn Pool
        - name: "CONMGR4_MAX_POOL_SIZE"
          lower:
            value: 10
          upper:
            value: 100
          step: 1
          real: False
        - name: "CONMGR4_MIN_POOL_SIZE"
          lower:
            value: 10
          upper:
            value: 100
            dependsOn: "CONMGR4_MAX_POOL_SIZE"
          step: 1
          real: False
        - name: "CONMGR4_TIMEOUT"
          lower:
            value: 1
          upper:
            value: 300
          step: 10
          real: False
        - name: "CONMGR4_AGED_TIMEOUT"
          lower:
            value: 1
          upper:
            value: 300
          step: 10
          real: False
        - name: "CONMGR4_MAX_IDLE_TIMEOUT"
          lower:
            value: 1
          upper:
            value: 300
          step: 30
          real: False
        - name: "CONMGR4_REAP_TIME"
          lower:
            value: 1
          upper:
            value: 300
            dependsOn: "CONMGR4_MAX_IDLE_TIMEOUT"
          step: 30
          real: False
        - name: "HTTP_MAX_KEEP_ALIVE_REQUESTS"
          lower:
            value: 4
            dependsOn: "MAX_THREADS"
          upper:
            value: 100
            dependsOn: "CONMGR1_MAX_POOL_SIZE"
          step: 10
          real: False
        - name: "HTTP_PERSIST_TIMEOUT"
          lower:
            value: 15
          upper:
            value: 45
          step: 5
          real: False
  - name: daytrader-config-jvm
    filename: "jvm.options"
    tunables:
      number:
        - name: "-Xms"
          lower:
            value: 8
          upper:
            value: 8192
            dependsOn: "-Xmx"
          step: 8
          real: False
        - name: "-Xmx"
          lower:
            value: 16
          upper:
            value: 8192
            dependsOn: "memory 0.50 *"
          step: 16
          real: False
        - name: "-Xmns"
          lower:
            value: 8
          upper:
            value: 8192
            dependsOn: "-Xms 0.8 *"
          step: 32
          real: False
        - name: "-Xmnx"
          lower:
            value: 8
            dependsOn: "-Xmns"
          upper:
            value: 8192
            dependsOn: "-Xmx 0.8 *"
          step: 32
          real: False
        - name: "-Xscmx"
          lower:
            value: 16
          upper:
            value: 512
            dependsOn: "-XX:SharedCacheHardLimit"
          step: 16
          real: False
        - name: "-XX:SharedCacheHardLimit"
          lower:
            value: 16
          upper:
            value: 512
          step: 16
          real: False
      boolean:
        - name: "-Xtune:virtualized"
      option:
        - name: "gc"
          values:
            - "-Xgcpolicy:gencon"
        - name: "container_support"
          values:
            - "-XX:+UseContainerSupport"
