{
 "title": "SmartTuning",
 "time": { "from": "2020-06-15T18:47:18.000Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "sampling_interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "percentile", "query": "0.1, 0.5, 0.9, 0.99, 1" }
  ]
 },
 "panels": [
  {
   "title": "rps / MB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rps/MB" }
   ],
   "targets": [
    {
     "expr": "quantile($percentile,rate(smarttuning_http_requests_total{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval]))  / (quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuning-.*\", name!~\".*POD.*\"}[$sampling_interval])) / 1024 / 1024)",
     "legendFormat": "rps / byte train"
    },
    {
     "expr": "quantile($percentile,rate(smarttuning_http_requests_total{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval])) / (quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningprod-.*\", name!~\".*POD.*\"}[$sampling_interval]))/1024/1024)",
     "legendFormat": "rps / byte prod"
    },
    {
     "expr": "quantile($percentile,rate(smarttuning_http_requests_total{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval])) / (quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningdefault-.*\", name!~\".*POD.*\"}[$sampling_interval]))/1024/1024)",
     "legendFormat": "rps / byte default"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "train"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "prod"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "default"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\", container=~\".*service.*\"}[$sampling_interval]))",
     "legendFormat": "app train"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\",container=~\".*service.*\"}[$sampling_interval]))",
     "legendFormat": "app default"
    },
    {
     "expr": " quantile($percentile, rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\",container=~\".*service.*\"}[$sampling_interval]))",
     "legendFormat": "app prod"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"jmeter-default\",name!~\".*POD.*\",}[$sampling_interval]))",
     "legendFormat": "jmeter default"
    },
    {
     "expr": "quantile($percentile, rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\",container=~\".*proxy.*\"}[$sampling_interval]))",
     "legendFormat": "proxy train"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\",container=~\".*proxy.*\"}[$sampling_interval]))",
     "legendFormat": "proxy prod"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\",container=~\".*proxy.*\"}[$sampling_interval]))",
     "legendFormat": "proxy default"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"jmeter-train\",name!~\".*POD.*\",}[$sampling_interval]))",
     "legendFormat": "jmeter train"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"jmeter-prod\",name!~\".*POD.*\",}[$sampling_interval]))",
     "legendFormat": "jmeter prod"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total{pod=~\"acmeair-db-.*\",name!~\".*POD.*\",}[$sampling_interval]))",
     "legendFormat": "mongo"
    },
    {
     "expr": "quantile($percentile,rate(container_cpu_usage_seconds_total[$sampling_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuning-.*\", name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "train"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningprod-.*\", name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "prod"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningdefault-.*\", name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "default"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuning-.*\", name!~\".*POD.*\",container=~\"service\"}[$sampling_interval]))",
     "legendFormat": "app train"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile, container_memory_working_set_bytes{pod=~\"acmeair-tuningprod-.*\", name!~\".*POD.*\", container=~\"service\"}[$sampling_interval]))",
     "legendFormat": "app prod"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningdefault-.*\", name!~\".*POD.*\", container=~\"service\"}[$sampling_interval]) )",
     "legendFormat": "app default"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuning-.*\", name!~\".*POD.*\", container=~\"proxy\"}[$sampling_interval]))",
     "legendFormat": "proxy train"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningprod-.*\", name!~\".*POD.*\", container=~\"proxy\"}[$sampling_interval]) )",
     "legendFormat": "proxy prod"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-tuningdefault-.*\", name!~\".*POD.*\", container=~\"proxy\"}[$sampling_interval]) )",
     "legendFormat": "proxy default"
    },
    {
     "expr": "quantile($percentile, quantile_over_time($percentile,container_memory_working_set_bytes{pod=~\"acmeair-db.*\", name!~\".*POD.*\"}[$sampling_interval]) )         ",
     "legendFormat": "mongo"
    }
   ]
  },
  {
   "title": "Error (5xx) rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile($percentile, rate(smarttuning_http_requests_total{code=~\"5..\",pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval]))/quantile($percentile, rate(smarttuning_http_requests_total{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "train"
    },
    {
     "expr": "quantile($percentile, rate(smarttuning_http_requests_total{code=~\"5..\",pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval]))/quantile($percentile, rate(smarttuning_http_requests_total{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "prod"
    },
    {
     "expr": "quantile($percentile, rate(smarttuning_http_requests_total{code=~\"5..\",pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval]))/quantile($percentile, rate(smarttuning_http_requests_total{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "default"
    }
   ]
  },
  {
   "title": "App Latency",
   "type": "graph",
   "description": "proxy/app round-trip",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile($percentile,rate(smarttuning_http_latency_seconds_sum{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval])) / quantile($percentile,rate(smarttuning_http_latency_seconds_count{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "train"
    },
    {
     "expr": "quantile($percentile,rate(smarttuning_http_latency_seconds_sum{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval])) / quantile($percentile,rate(smarttuning_http_latency_seconds_count{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "prod"
    },
    {
     "expr": "quantile($percentile,rate(smarttuning_http_latency_seconds_sum{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval])) / quantile($percentile,rate(smarttuning_http_latency_seconds_count{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "default"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "\nquantile($percentile,rate(smarttuning_http_requests_total{pod=~\"acmeair-tuning-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "train"
    },
    {
     "expr": "quantile($percentile,rate(smarttuning_http_requests_total{pod=~\"acmeair-tuningprod-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "prod"
    },
    {
     "expr": "quantile($percentile,rate(smarttuning_http_requests_total{pod=~\"acmeair-tuningdefault-.*\",name!~\".*POD.*\"}[$sampling_interval]))",
     "legendFormat": "default"
    }
   ]
  }
 ]
}