{
 "title": "smarttuning-replicas2",
 "time": { "from": "2022-08-10T13:27:50.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   },
   {
    "name": "time_interval_m",
    "query": "30s,1m,100s,200s,5m,6m,400s,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "prod_podname",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   },
   {
    "name": "train_podname",
    "query": {
     "query": "container_cpu_usage_seconds_total"
    }
   }
  ]
 },
 "panels": [
  { "title": "smarttuning metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$prod_podname\"}[$time_interval_m])",
     "legendFormat": "PROD"
    },
    {
     "expr": "avg_over_time(kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$train_podname\"}[$time_interval_m])",
     "legendFormat": "TRAIN"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", namespace=~\"$namespace\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[2|3]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(vendor_servlet_request_total{pod=~\"$prod_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m]))\n",
     "legendFormat": "sPROD $prod_podname"
    },
    {
     "expr": "sum(rate(vendor_servlet_request_total{pod=~\"$train_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m]))",
     "legendFormat": "sTRAIN $train_podname"
    },
    {
     "expr": "sum(rate(base_REST_request_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m]))",
     "legendFormat": "sPROD $prod_podname"
    },
    {
     "expr": "sum(rate(base_REST_request_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m]))",
     "legendFormat": "sTRAIN $train_podname"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "avg(rate(smarttuning_http_processtime_seconds_sum{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_processtime_seconds_count{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "avg(sum(rate(vendor_servlet_responseTime_total_seconds{pod=~\"$prod_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])/rate(vendor_servlet_request_total{pod=~\"$prod_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])) by (pod))",
     "legendFormat": "sPROD $prod_podname"
    },
    {
     "expr": "avg(sum(rate(vendor_servlet_responseTime_total_seconds{pod=~\"$train_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])/rate(vendor_servlet_request_total{pod=~\"$train_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])) by (pod))",
     "legendFormat": "sTRAIN $train_podname"
    },
    {
     "expr": "avg(deriv(base_REST_request_elapsedTime_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m]))",
     "legendFormat": "sPROD $prod_podname"
    },
    {
     "expr": "avg(deriv(base_REST_request_elapsedTime_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m]))",
     "legendFormat": "sTRAIN $train_podname"
    }
   ]
  },
  {
   "title": "objective -- [1/(1+resp time)] * [throughput /(n * cost)]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1/(1+avg(sum(rate(vendor_servlet_responseTime_total_seconds{pod=~\"$prod_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])/rate(vendor_servlet_request_total{pod=~\"$prod_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])) by (pod)))) * (sum(rate(vendor_servlet_request_total{pod=~\"$prod_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m]))/(((sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        ((sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^30))))",
     "legendFormat": "sProd"
    },
    {
     "expr": "(1/(1+avg(sum(rate(vendor_servlet_responseTime_total_seconds{pod=~\"$train_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])/rate(vendor_servlet_request_total{pod=~\"$train_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m])) by (pod)))) * (sum(rate(vendor_servlet_request_total{pod=~\"$train_podname-.*\",servlet!~\"com_ibm_ws_microprofile.*|.*Trade.*\"}[$time_interval_m]))/(((sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        ((sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^30))))",
     "legendFormat": "sTrain"
    },
    {
     "expr": "(1/(1+avg(deriv(base_REST_request_elapsedTime_seconds{pod=~\"$prod_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m])))) * (sum(rate(base_REST_request_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m]))/(((sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        ((sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^30))))",
     "legendFormat": "sProd"
    },
    {
     "expr": "(1/(1+avg(deriv(base_REST_request_elapsedTime_seconds{pod=~\"$train_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m])))) * (sum(rate(base_REST_request_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\",class=\"com.acme.crud.FruitResource\"}[$time_interval_m]))/(((sum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))/ avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])))+\n        ((sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))) / 2^30))))",
     "legendFormat": "sTrain"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))",
     "legendFormat": "prod + train"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\".*-db-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))",
     "legendFormat": "database"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"smarttuning-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m]))",
     "legendFormat": "smarttuning"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{id=~\".*kubepods.*\",pod=~\"jmeter-prod.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "jmeter"
    }
   ]
  },
  {
   "title": "Memory - container size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) \n",
     "legendFormat": "PROD"
    },
    {
     "expr": "sum(max_over_time(container_spec_memory_limit_bytes{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) ",
     "legendFormat": "TRAIN"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])) \n",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])) ",
     "legendFormat": "TRAIN $train_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"$prod_podname.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "prod + train"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\".*-db-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "database"
    },
    {
     "expr": "\nsum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) / avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\",container=~\"\"}[$time_interval_m]))\n",
     "legendFormat": "limit $prod_podname"
    },
    {
     "expr": "\nsum(sum_over_time(container_spec_cpu_quota{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\", container=\"\"}[$time_interval_m])) / avg(sum_over_time(container_spec_cpu_period{id=~\".*kubepods.*\",pod=~\"$train_podname-.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m]))\n",
     "legendFormat": "limit $train_podname"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=~\".*kubepods.*\",pod=~\"jmeter-prod.*\",name!~\".*POD.*\",container=\"\"}[$time_interval_m])) ",
     "legendFormat": "jmeter"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_requests_total{pod=~\"$prod_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "PROD $prod_podname"
    },
    {
     "expr": "sum(rate(smarttuning_http_requests_total{code=~\"[4|5]..\",pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m])) / sum( rate(smarttuning_http_requests_total{pod=~\"$train_podname-.*\",name!~\".*POD.*\"}[$time_interval_m]))",
     "legendFormat": "TRAIN $train_podname"
    }
   ]
  }
 ]
}