apiVersion: v1
data:
  CONMGR1_AGED_TIMEOUT: "41"
  CONMGR1_CONN_PER_THREAD: "1"
  CONMGR1_MAX_IDLE_TIMEOUT: "121"
  CONMGR1_MAX_POOL_SIZE: "29"
  CONMGR1_MIN_POOL_SIZE: "11"
  CONMGR1_PURGE_POLICY: FailingConnectionOnly
  CONMGR1_REAP_TIME: "31"
  CONMGR1_TIMEOUT: "21"
  CONMGR3_AGED_TIMEOUT: "0"
  CONMGR3_CONN_PER_THREAD: "1"
  CONMGR3_MAX_IDLE_TIMEOUT: "1"
  CONMGR3_MAX_POOL_SIZE: "10"
  CONMGR3_MIN_POOL_SIZE: "4"
  CONMGR3_PURGE_POLICY: FailingConnectionOnly
  CONMGR3_REAP_TIME: "1"
  CONMGR3_TIMEOUT: "0"
  CONMGR4_AGED_TIMEOUT: "211"
  CONMGR4_CONN_PER_THREAD: "1"
  CONMGR4_MAX_IDLE_TIMEOUT: "121"
  CONMGR4_MAX_POOL_SIZE: "22"
  CONMGR4_MIN_POOL_SIZE: "4"
  CONMGR4_PURGE_POLICY: FailingConnectionOnly
  CONMGR4_REAP_TIME: "1"
  CONMGR4_TIMEOUT: "171"
  CORE_THREADS: "0"
  HTTP_MAX_KEEP_ALIVE_REQUESTS: "27"
  HTTP_PERSIST_TIMEOUT: "20"
  HTTP_READ_TIMEOUT: "60"
  HTTP_WRITE_TIMEOUT: "60"
  MAX_THREADS: "27"
  ORDER_PROCESSING_MODE: "0"
  RUNTIME_MODE: "1"
  WEB_INTERFACE: "0"
kind: ConfigMap
metadata:
  name: daytrader-config-app
  namespace: default
---
apiVersion: v1
data:
  jvm.options: |-
    -Xmns104m
    -Xmnx136m
    -Xmx208m
    -Xms160m
    -XX:SharedCacheHardLimit=208m
    -Xscmx=96m
    -Xgcpolicy:gencon
    -XX:+UseContainerSupport
kind: ConfigMap
metadata:
  name: daytrader-config-jvm
  namespace: default
