---
#### Daytrader Database  #####
apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-db
  name: daytrader-db
spec:
  type: NodePort
  ports:
    - name: "db2"
      port: 50000
      protocol: TCP
      targetPort: 50000
      nodePort: 30050
    - name: "derby"
      port: 1527
      protocol: TCP
      targetPort: 1527
      nodePort: 30051
  selector:
    app: daytrader-db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: daytrader
  name: daytrader-full
spec:
  #  clusterIP: None
  ports:
  - name: https
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: daytrader
status:
  loadBalancer: {}
