apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-config
data:
  JVM_ARGS: "-Xms1g -Xmx1g -Xtune:virtualized -XX:+UseContainerSupport -XX:MaxRAMPercentage=90"
  JTOPUID: "199"
  JPORT: "9080"
  JMAXTHINKTIME: "50"
  JSTOCKS: "499"
  JTHREADS: "2000"
  JSTEPTHREADS: "50"
  JTHROUGHPUT: "100"
  JRATIO: ".8"
  JRAMP: "10"
  #JDURATION: "57600"
  #JDURATION: "3600"
  JDURATION: "259200"
  #JDURATION: "64800"
  JSELLS: "4"
  JBUYS: "4"
  JQUOTES: "44"
  TEST_GROUP: "replicas-periodic"
  #TEST_GROUP: "replicas-test-linear"
  #TEST_GROUP: "all"
  #"browsing-jsp,trading-jsp,jsp,jsf,all,jax,replicas,replicas-test-step,replicas-test-linear,replicas-periodic"
  TEST_PLAN: "dynamic_daytrader8.jmx"
