# acmeair/metric_fetcher

FROM python:3
RUN mkdir app
WORKDIR app
RUN export PATH=$PATH:/app

COPY fetching/requirements.txt ./
RUN pip install -r requirements.txt
COPY fetching/run-workload.sh ./
RUN chmod a+x run-workload.sh
COPY common ./common
COPY fetching/acmeair_workload.py ./

ENV PROMETHEUS_URL=localhost
ENV PROMETHEUS_PORT=9090
ENV MONGO_URL=localhost
ENV MONGO_PORT=27017
ENV FETCH_WINDOW=5
ENV TIME_UNIT=seconds
ENV DB_NAME=acmeair_hist
ENV DB_COLLECTION=acmeair_hist_c1
ENV DB_BUFFER_SIZE=10
ENV METRIC_NAME=memory
#ENV METRIC_NAME=cpu
#ENV METRIC_NAME=threads
#ENV METRIC_NAME=http
#ENV METRIC_NAME=throughput
#ENV METRIC_NAME=response_time
ENV METRIC_QUERY='(base_memory_usedHeap_bytes/base_memory_maxHeap_bytes)'
#ENV METRIC_QUERY='base_cpu_processCpuLoad_percent'
#ENV METRIC_QUERY='vendor_threadpool_size{pool="LargeThreadPool"}'
#ENV METRIC_QUERY='increase(application_currentHttpConnections[15s])'
#ENV METRIC_QUERY='rate(vendor_servlet_request_total{servlet="acmeair_webapp_com_acmeair_web_AcmeAirApp"}[15s])'
#ENV METRIC_QUERY='rate(vendor_servlet_responseTime_total_seconds{servlet="acmeair_webapp_com_acmeair_web_AcmeAirApp"}[15s])/rate(vendor_servlet_request_total{servlet="acmeair_webapp_com_acmeair_web_AcmeAirApp"}[15s])'

ENTRYPOINT ["./run-workload.sh"]
