version: "2"

services:
  fetcher_histogram:
      image: acmeair/hist_fetcher
      cpuset: "1"
      networks:
          - default
      environment:
          - PROMETHEUS_URL=prometheus
          - MONGO_URL=mongodb
          - DB_NAME=acmeair_db_experiments
          - DB_COLLECTION=acmeair_collection_histogram
          - FETCH_WINDOW=60
          - TIME_UNIT=seconds
          - BUFFER_SIZE=0

networks:
    default:
        external:
            name: acmeair-network
