FROM python:3
RUN mkdir app
WORKDIR app
RUN export PATH=$PATH:/app

COPY fetching/requirements.txt ./
RUN pip install -r requirements.txt
COPY fetching/run-workflow.sh ./
RUN chmod a+x run-workflow.sh
COPY common ./common
COPY fetching/acmeair_workflow.py ./

ENV PROMETHEUS_URL=localhost
ENV PROMETHEUS_PORT=9090
ENV MONGO_URL=localhost
ENV MONGO_PORT=27017
ENV FETCH_WINDOW=5
ENV TIME_UNIT=seconds
ENV DB_NAME=acmeair_hist
ENV DB_COLLECTION=acmeair_hist_c1
ENV DB_BUFFER_SIZE=10

ENTRYPOINT ["./run-workflow.sh"]
