# Dockerfile to build a jmeter container able to drive acmeair
# Results appear on /output in the container
# Must specify the hostname for the acmeair application (or localhost will be assumed)
FROM smarttuning/jmeter_plain
#FROM ibmjava:8-jre
#
#
##ENV JMETER_VERSION 2.13
#ENV JMETER_VERSION 5.2.1
## Install pre-requisite packages
#RUN apt-get update && apt-get install -y --no-install-recommends wget unzip curl inetutils-ping \
#       && rm -rf /var/lib/apt/lists/*
#
## Install jmeter
#RUN   mkdir /jmeter \
#        && mkdir /output \
#        # uncomment lines below for a fresh installation
#        && cd /jmeter/
#        #&& wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
#        #&& tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
#        #&& rm apache-jmeter-$JMETER_VERSION.tgz
#COPY apache-jmeter-$JMETER_VERSION /jmeter/apache-jmeter-$JMETER_VERSION
## Set jmeter home, add jmeter to the PATH and set JVM options
#ENV JMETER_HOME="/jmeter/apache-jmeter-$JMETER_VERSION"
#ENV PATH="$JMETER_HOME/bin:$PATH"
#ENV JVM_ARGS="-Xms1g -Xmx1g -Xtune:virtualized -XX:+UseContainerSupport -XX:MaxRAMPercentage=90"
#
## We should set summariser.interval=6 in bin/jmeter.properties
#RUN echo 'summariser.interval=6' >> $JMETER_HOME/bin/jmeter.properties

# Copy the script to be executed and other needed files
COPY DriverFiles/ $JMETER_HOME/
COPY DriverFiles/applyLoad.sh $JMETER_HOME/bin/applyLoad.sh
COPY DriverFiles/toggle-test.sh $JMETER_HOME/bin/toggle-test.sh
COPY DriverFiles/init.sh $JMETER_HOME/bin/init.sh

RUN chmod u+x $JMETER_HOME/bin/toggle-test.sh && \
    chmod u+x $JMETER_HOME/bin/applyLoad.sh && \
    chmod u+x $JMETER_HOME/bin/init.sh

# Adjust the host this is going to connect to based on an environment variable
ENV LIBERTYHOST=localhost

# Environment variables that we want the user to redefine
ENV JPORT=9090 \
    JUSERS=200 \
    JUSERBOTTOM=0 \
    JUSER=199 \
    JURL=acmeair-webapp \
    JTHREAD=10 \
    JDURATION=60 \
    JREPEAT=1 \
    JRAMPUP=0 \
    JLOAD_BOOKINGS=true \
    JWAIT=0 \
    JMIN_SESSION_DURATION=0 \
    JMAX_SESSION_DURATION=60 \
    JMIN_THINK=100\
    JMAX_THINK=200\
    JTARGET_THROUGHPUT=6000 \
    THREAD_GROUP=workload-uniform \
    TEST_PLAN=tuning-workloads.jmx

EXPOSE 9270

ENTRYPOINT ["/bin/bash", "-c", "init.sh"]
