apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-config
data:
  JTOPUID: "199"
  JPORT: "9080"
  JMAXTHINKTIME: "0"
  JSTOCKS: "499"
  JTHREADS: "50"
  JRAMP: "10"
  JDURATION: "259200"
  JSELLS: "4"
  JBUYS: "4"
  JQUOTES: "44"