apiVersion: v1
kind: ConfigMap
metadata:
  name: daytrader-config-app
  namespace: daytrader-jspjsf
data:
  HTTP_MAX_KEEP_ALIVE_REQUESTS: "100"
  HTTP_PERSIST_TIMEOUT: "30"
  HTTP_READ_TIMEOUT: "60"
  HTTP_WRITE_TIMEOUT: "60"
  CONMGR1_TIMEOUT: "30"
  CONMGR1_AGED_TIMEOUT: "280"
  CONMGR1_MAX_IDLE_TIMEOUT: "270"
  CONMGR1_REAP_TIME: "180"
  CONMGR1_MAX_POOL_SIZE: "10"
  CONMGR1_MIN_POOL_SIZE: "4"
  CONMGR1_PURGE_POLICY: "FailingConnectionOnly"
  CONMGR1_CONN_PER_THREAD: "1"
  CONMGR3_TIMEOUT: "0"
  CONMGR3_AGED_TIMEOUT: "0"
  CONMGR3_MAX_IDLE_TIMEOUT: "1"
  CONMGR3_REAP_TIME: "1"
  CONMGR3_MAX_POOL_SIZE: "10"
  CONMGR3_MIN_POOL_SIZE: "4"
  CONMGR3_PURGE_POLICY: "FailingConnectionOnly"
  CONMGR3_CONN_PER_THREAD: "1"
  CONMGR4_TIMEOUT: "30"
  CONMGR4_AGED_TIMEOUT: "280"
  CONMGR4_MAX_IDLE_TIMEOUT: "270"
  CONMGR4_REAP_TIME: "180"
  CONMGR4_MAX_POOL_SIZE: "10"
  CONMGR4_MIN_POOL_SIZE: "4"
  CONMGR4_PURGE_POLICY: "FailingConnectionOnly"
  CONMGR4_CONN_PER_THREAD: "1"
  CORE_THREADS: "0"
  MAX_THREADS: "10"
  ORDER_PROCESSING_MODE: "0"
  RUNTIME_MODE: "1"
  WEB_INTERFACE: "0"
