apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader-db
  labels:
    app: daytrader-db
spec:
  replicas: 1
  template:
    metadata:
      name: daytrader-db
      labels:
        app: daytrader-db
    spec:
      volumes:
        - name: db2-volume
          emptyDir: {}
      containers:
        # use su - db2inst1 when inspecting the container
        - name: daytrader-db
          image: smarttuning/db2
          volumeMounts:
            - mountPath: /database
              name: db2-volume
          securityContext:
            privileged: true
          env:
            - name: LICENSE
              value: accept
            - name: DB2COMM
              value: tcpip
            - name: DB2INST1_PASSWORD
              value: db2pass
          ports:
            - containerPort: 50000
              protocol: TCP
  selector:
    matchLabels:
      app: daytrader-db
