---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: smarttuning
  name: smarttuning
  namespace: daytrader-jspjsf
spec:
  ports:
  - name: smarttuning
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: smarttuning
---
