apiVersion: v1
kind: Service
metadta:
  name: jmeter-prod
  labels:
    app: jmeter-prod
spec:
  type: NodePort
  ports:
    - port: 9270
      name: http
  selector:
    app: jmeter-prod
---
apiVersion: v1
kind: Pod
metadata:
  name: jmeter-prod
  labels:
    app: jmeter-prod
  annotations:
    prometheus.io/scrape: "true"
      #prometheus.io/path: "/metrics"
    prometheus.io/port: "9270"

spec:
  containers:
    - name: jmeter-prod
      image: smarttuning/jmeter_daytrader
#      resources:
#        limits:
#          cpu: "2"
      lifecycle:
        preStop:
          exec:
            command:
              - "sh"
              - "-c"
              - |
                shutdown.sh
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9270
      env:
        - name: JHOST
          value: 'daytrader.default.svc.cluster.local'
      envFrom:
        - configMapRef:
            name: jmeter-config
      volumeMounts:
        - mountPath: /etc/jmeter
          name: jmeter-config
        - mountPath: /output-prod
          name: jmeter-output
  terminationGracePeriodSeconds: 5
  volumes:
    - name: jmeter-config
      configMap:
        name: jmeter-config
    - name: jmeter-output
      hostPath:
        path: /smarttuning/jmeter/prod
  restartPolicy: Never



