apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
    date: "1617412657"
  name: daytrader-config-jvm
  namespace: default
data:
  jvm.options: |-
    -Xmn128m
    -Xmx344m
    -Xms168m
    -XX:SharedCacheHardLimit=304m
    -Xscmx=128m
    -Xtune:virtualized
    -Xgcpolicy:gencon
    -XX:+UseContainerSupport
