---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-svc
  labels:
    app: quarkus-svc
  annotations:
    injection.smarttuning.ibm.com: "true"
spec:
  ports:
  - nodePort: 30088
    port: 9080
    targetPort: 9080
    name: http
  selector:
    app: quarkus-service
    smarttuning: "false"
  type: NodePort
status:
  loadBalancer: {}
---
