apiVersion: "smarttuning.ibm.com/v1alpha2"
kind: SearchSpace
metadata:
  name: acmeair-ss
spec:
  deployment: acmeair-service
  service: acmeair-svc
  namespace: "default"
  manifests:
    - name: acmeair-service
      type: "deployment"
    - name: acmeair-config-app
      type: "configMap"
    - name: acmeair-config-jvm
      type: "configMap"
data:
  - name: acmeair-service
    tunables:
      option:
        - name: "cpu"
          type: "integer"
          values:
            - "2"
            - "4"
            - "8"
#            - "16"
        - name: "memory"
          type: "integer"
          values:
            - "512"
            - "1024"
            - "2048"
            - "4096"
            - "8192"
  - name: acmeair-config-app
    tunables:
      number:
        - name: "HTTP_MAX_KEEP_ALIVE_REQUESTS"
          lower:
            value: 10
          upper:
            value: 200
          step: 25
          real: False
        - name: "HTTP_PERSIST_TIMEOUT"
          lower:
            value: 15
          upper:
            value: 45
          step: 5
          real: False
        - name: "MONGO_MAX_CONNECTIONS"
          lower:
            value: 10
          upper:
            value: 200
          step: 25
          real: False
  - name: acmeair-config-jvm
    filename: "jvm.options"
    tunables:
      boolean:
        - name: "-Xtune:virtualized"
      option:
        - name: "gc"
          values:
            - "-Xgcpolicy:gencon"
            - "-Xgcpolicy:concurrentScavenge"
            - "-Xgcpolicy:metronome"
            - "-Xgcpolicy:optavgpause"
            - "-Xgcpolicy:optthruput"
        - name: "container_support"
          values:
            - "-XX:+UseContainerSupport"
            - "-XX:-UseContainerSupport"
