apiVersion: v1
kind: ConfigMap
metadata:
  name: jvm-config-test
data:
  jvm.options: |
    -Xmx256m
    -Dhttp.keepalive=true
    -Dhttp.maxConnections=100
---
apiVersion: "smarttuning.ibm.com/v1alpha1"
kind: SearchSpace
metadata:
  name: jvm-test
spec:
  manifests:
    - name: "jvm-config-test"
      nameProd: "jvm-config-testprod"
      namespace: "default"
      type:
        configMap: "jvm"
        filename: "jvm.options"
      params:
        - name: "-Dhttp.keepalive"
          boolean: true
        - name: "-Dhttp.maxConnections"
          number:
            lower: 10
            upper: 200
            step: 10
            continuous: false
        - name: "gc"
          options:
            type: string
            values:
              - "-Xgcpolicy:gencon"
              - "-Xgc:concurrentScavenge"
              - "-Xgcpolicy:metronome"
              - "-Xgcpolicy:optavgpause"
              - "-Xgcpolicy:optthruput"
        - name: "virtualized"
          options:
            type: string
            values:
              - "-Xtune:virtualized"
        - name: "container_support"
          options:
            type: string
            values:
              - "-XX:+UseContainerSupport"
              - "-XX:-UseContainerSupport"