# https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: searchspaces.smarttuning.ibm.com
spec:
  group: smarttuning.ibm.com
  scope: Namespaced
  names:
    plural: searchspaces
    singular: searchspace
    kind: SearchSpace
    shortNames:
      - ss
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                manifests:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        description: "training manifest name"
                        type: string
                      nameProd:
                        descpription: "production manifest name"
                        type: string
                      namespace:
                        description: "namespace where manifest is deployed"
                        type: string
                      type:
                        type: object
                        properties:
                          deployment:
                            type: boolean
                            default: false
                          containers:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                ratio:
                                  type: number
                          configMap:
                            type: string
                            description: "is it data a config file (file) or environment variables (envVar)?"
                            pattern: '(jvm|envVar)'
                          filename:
                            type: string
                            description: "if configMap is file, then assign its name here"
                            default: ''
                      params:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            number:
                              type: object
                              properties:
                                lower:
                                  type: number
                                upper:
                                  type: number
                                step:
                                  type: number
                                continuous:
                                  type: boolean
                                  default: true
                            boolean:
                              type: boolean
                              default: False
                            options:
                              type: object
                              properties:
                                type:
                                  type: string
                                  pattern: '(number|boolean|string)'
                                values:
                                  type: array
                                  items:
                                    type: string
                        oneOf:
                          - required: ["number", "boolean", "options"]
                        required: ["params"]
#---
#apiVersion: "smarttuning.ibm.com/v1alpha1"
#kind: SearchSpace
#metadata:
#  name: test
#spec:
#  manifests:
#    - name: "acmeair-tuning"
#      nameProd: "acmeair-tuningprod"
#      namespace: "default"
#      type:
#        deployment: true
#        containers:
#          - name: "proxy"
#            ratio: 0.1
#          - name: "service"
#            ratio: 0.9
#      params:
#        - name: "cpu"
#          number:
#            lower: 1
#            upper: 15
#            step: 0.5
#            continuous: true
#        - name: "memory"
#          number:
#            lower: 256
#            upper: 512
#            step: 16
#            continuous: false
#    - name: "jvm-config-train"
#      nameProd: "jvm-config-prod"
#      namespace: "default"
#      type:
#        configMap: "jvm"
#        filename: "jvm.options"
#      params:
#        - name: "gc"
#          options:
#            type: string
#            values:
#              - "-Xgcpolicy:gencon"
#              - "-Xgc:concurrentScavenge"
#              - "-Xgcpolicy:metronome"
#              - "-Xgcpolicy:optavgpause"
#              - "-Xgcpolicy:optthruput"
#        - name: "virtualized"
#          options:
#            type: string
#            values:
#              - "-Xtune:virtualized"
#        - name: "container_support"
#          options:
#            type: string
#            values:
#              - "-XX:+UseContainerSupport"
#              - "-XX:-UseContainerSupport"
#    - name: "acmeair-config-train"
#      nameProd: "acmeair-config-prod"
#      namespace: "default"
#      type:
#        configMap: "envVar"
#      params:
#        - name: "MONGO_CONNECTION_TIMEOUT"
#          number:
#            lower: 10
#            upper: 30
#            step: 1
#            continuous: false
#        - name: "MONGO_MAX_CONNECTIONS"
#          number:
#            lower: 4
#            upper: 300
#            step: 10
#            continuous: false
#        - name: "HTTP_MAX_KEEP_ALIVE_REQUESTS"
#          number:
#            lower: 4
#            upper: 300
#            step: 10
#            continuous: false
