apiVersion: v1
data:
  CONMGR1_AGED_TIMEOUT: "81"
  CONMGR1_CONN_PER_THREAD: "1"
  CONMGR1_MAX_IDLE_TIMEOUT: "151"
  CONMGR1_MAX_POOL_SIZE: "44"
  CONMGR1_MIN_POOL_SIZE: "40"
  CONMGR1_PURGE_POLICY: FailingConnectionOnly
  CONMGR1_REAP_TIME: "31"
  CONMGR1_TIMEOUT: "171"
  CONMGR3_AGED_TIMEOUT: "0"
  CONMGR3_CONN_PER_THREAD: "1"
  CONMGR3_MAX_IDLE_TIMEOUT: "1"
  CONMGR3_MAX_POOL_SIZE: "10"
  CONMGR3_MIN_POOL_SIZE: "4"
  CONMGR3_PURGE_POLICY: FailingConnectionOnly
  CONMGR3_REAP_TIME: "1"
  CONMGR3_TIMEOUT: "0"
  CONMGR4_AGED_TIMEOUT: "121"
  CONMGR4_CONN_PER_THREAD: "1"
  CONMGR4_MAX_IDLE_TIMEOUT: "91"
  CONMGR4_MAX_POOL_SIZE: "28"
  CONMGR4_MIN_POOL_SIZE: "24"
  CONMGR4_PURGE_POLICY: FailingConnectionOnly
  CONMGR4_REAP_TIME: "91"
  CONMGR4_TIMEOUT: "191"
  CORE_THREADS: "0"
  HTTP_MAX_KEEP_ALIVE_REQUESTS: "42"
  HTTP_PERSIST_TIMEOUT: "25"
  HTTP_READ_TIMEOUT: "60"
  HTTP_WRITE_TIMEOUT: "60"
  MAX_THREADS: "22"
  ORDER_PROCESSING_MODE: "0"
  RUNTIME_MODE: "1"
  WEB_INTERFACE: "0"
kind: ConfigMap
metadata:
  name: daytrader-config-app
  namespace: default
---
apiVersion: v1
data:
  jvm.options: |-
    -Xmns72m
    -Xmnx168m
    -Xmx336m
    -Xms96m
    -XX:SharedCacheHardLimit=192m
    -Xscmx=144m
    -Xgcpolicy:gencon
    -XX:+UseContainerSupport
kind: ConfigMap
metadata:
  name: daytrader-config-jvm
  namespace: default
