apiVersion: v1
kind: Service
metadata:
  name: jmeter-teastore
  namespace: teastore
  labels:
    app: jmeter-teastore
spec:
  type: NodePort
  ports:
    - port: 9270
      targetPort: 9270
      name: smarttuning
  selector:
    app: jmeter-teastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "9270"
  labels:
    app: jmeter-teastore
  name: jmeter-teastore
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-teastore
  template:
    metadata:
      labels:
        app: jmeter-teastore
    spec:
      containers:
      - image: "smarttuning/jmeter-teastore:icse"
        name: jmeter-teastore
        ports:
          - containerPort: 9270
            name: http
        imagePullPolicy: IfNotPresent
        env:
          - name: JHOST
            value: 'teastore-all.teastore.svc.cluster.local'
        envFrom:
          - configMapRef:
              name: jmeter-cm-teastore
