---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tuning
  namespace: quarkus
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tuning
  namespace: quarkus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tuning
subjects:
  - kind: ServiceAccount
    name: default
    namespace: quarkus
---

