# only works on version 3.7
FROM python:3.7

WORKDIR /usr/src/app
RUN pip install --no-cache-dir hyperopt pymongo
ENV MONGO=
# MONGO=localhost:27917/snd
CMD ["sh", "-c",  "hyperopt-mongo-worker --mongo=$MONGO --poll-interval=1"]
