FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY reloader.py reloader.py
COPY sync.py app.py

#ENV FLASK_APP=/usr/src/app/app.py
EXPOSE 5000

#ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
ENTRYPOINT ["python", "-u", "app.py"]