apiVersion: v1
kind: ConfigMap
metadata:
  namespace: acmeair
  name: acmeair-configmap
data:
  # Mongo specific
  MONGO_HOST: "mongo-acmeair-service.acmeair.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DBNAME: "acmeair"
  # default MONGO_MAX_CONNECTIONS=100
  MONGO_MAX_CONNECTIONS: "100"
  # Overload related
  OVERHEAD_CHANCE: "0.0"
  #CPU_LOAD: 0.3
  MEMORY_LOAD: "20485761"
  SERVER_PORT: "80"
  USE_FLIGHT_DATA_RELATED_CACHING: "false"
  LOG_DIR: "/logs"
  WLP_LOGGING_CONSOLE_FORMAT: "basic"
  WLP_LOGGING_CONSOLE_LOGLEVEL: "info"
  # JVM specific
  #JVM_ARGS=""-Xms128M -Xmx128M""
  JVM_ARGS: '"-Xms128M -Xmx128M -Xtune:virtualized -XX:+UseContainerSupport"'
  # Openliberty specific
  # default (100, 30, -1, -1)
  MAX_KEEP_ALIVE_REQUESTS: "100"
  PERSIST_TIMEOUT: "30"
  CORE_THREADS: "4"
  MAX_THREADS: "4"

