apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader-db
  labels:
    app: daytrader-db
spec:
  replicas: 1
  template:
    metadata:
      name: daytrader-db
      labels:
        app: daytrader-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kind-worker9
                      - docker-desktop
      volumes:
        - name: db2-volume
#          emptyDir: {}
          emptyDir:
            medium: "Memory"
#          hostPath:
#            type: DirectoryOrCreate
#            path: /database
      containers:
        # use su - db2inst1 when inspecting the container
        - name: daytrader-db
          image: smarttuning/derby
          volumeMounts:
            - mountPath: /data
              name: db2-volume
          securityContext:
            privileged: true
          ports:
            - containerPort: 1527
              protocol: TCP
#          resources:
#            limits:
#              cpu: "16"
#              memory: "8Gi"
#      restartPolicy: Always
  selector:
    matchLabels:
      app: daytrader-db
