apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader-db
  labels:
    app: daytrader-db
spec:
  replicas: 1
  template:
    metadata:
      name: daytrader-db
      labels:
        app: daytrader-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kind-worker9
                      - docker-desktop
      volumes:
        - name: db2-volume
#          emptyDir: {}
#          emptyDir:
#            medium: "Memory"
          hostPath:
            type: DirectoryOrCreate
            path: /database
      containers:
        # use su - db2inst1 when inspecting the container
        - name: daytrader-db
          image: smarttuning/db2
          volumeMounts:
            - mountPath: /database
              name: db2-volume
          securityContext:
            privileged: true
          env:
            - name: LICENSE
              value: accept
            - name: DB2COMM
              value: tcpip
            - name: "DB2_LOGGER_NON_BUFFERED_IO"
              value: "OFF"
#            - name: DB2_DEFERRED_PREPARE_SEMANTICS
#              value: "YES"
#            - name: DB2_COMPATIBILITY_VECTOR
#              value: ORA
            - name: DB2INST1_PASSWORD
              value: db2pass
          ports:
            - containerPort: 50000
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: "16Gi"
#      restartPolicy: Always
  selector:
    matchLabels:
      app: daytrader-db
