apiVersion: apps/v1
kind: Deployment
metadata:
  name: daytrader-db
  labels:
    app: daytrader-db
spec:
  replicas: 1
  template:
    metadata:
      name: daytrader-db
      labels:
        app: daytrader-db
    spec:
      volumes:
        - name: db2-volume
          emptyDir:
            medium: "Memory"
      containers:
        - name: daytrader-db
          image: smarttuning/derby
          volumeMounts:
            - mountPath: /data
              name: db2-volume
          securityContext:
            privileged: true
          ports:
            - containerPort: 1527
              protocol: TCP
  selector:
    matchLabels:
      app: daytrader-db
