# make it reacheable by prometheus
apiVersion: v1
kind: Service
metadata:
  name: daytrader
  namespace: daytrader
  annotations:
    injection.smarttuning.ibm.com: "false"
  labels:
    app: daytrader
    smarttuning: "false"
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 493
      name: https
        #   - nodePort: 30088
    - port: 9080
      targetPort: 9080
      name: http
  selector:
    app: daytrader
    smarttuning: "false"
---
#### Daytrader Database  #####
apiVersion: v1
kind: Service
metadata:
  labels:
    app: daytrader-db
  name: daytrader-db
  namespace: daytrader
spec:
  type: NodePort
  ports:
    - name: "db2"
      port: 50000
      protocol: TCP
      targetPort: 50000
      nodePort: 30050
    - name: "derby"
      port: 1527
      protocol: TCP
      targetPort: 1527
      nodePort: 30051
  selector:
    app: daytrader-db
status:
  loadBalancer: {}
