apiVersion: v1
kind: Pod
metadata:
  labels:
    run: teastore-db
  name: teastore-db
  namespace: teastore
spec:
  containers:
  - image: descartesresearch/teastore-db
    imagePullPolicy: IfNotPresent
    name: teastore-db
    ports:
    - containerPort: 3306
      protocol: TCP
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: teastore-db
  name: teastore-db
  namespace: teastore
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: teastore-db
  type: ClusterIP
