apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    injection.smarttuning.ibm.com: "true"
  labels:
    run: teastore-all
  name: teastore-all
  namespace: teastore
spec:
  replicas: 1
  selector:
    matchLabels:
      smarttuning: "false"
      run: teastore-all
  strategy: {}
  template:
    metadata:
      labels:
        smarttuning: "false"
        run: teastore-all
    spec:
      containers:
      - image: descartesresearch/teastore-all
        imagePullPolicy: IfNotPresent
        name: teastore-all
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: "512Mi"
              #         readinessProbe:
              #           httpGet:
              #             path: /tools.descartes.teastore.webui
              #             port: 8080
              #           initialDelaySeconds: 30
              #           periodSeconds: 15
              #        startupProbe:
              #          httpGet:
              #            port: 8080
              #            path: /tools.descartes.teastore.webui
              #          initialDelaySeconds: 120
              #          periodSeconds: 30
        volumeMounts:
          - name: tomcat-config
            mountPath: /usr/local/tomcat/conf/server.xml
            subPath: server.xml
          - name: tomcat-config
            mountPath: /usr/local/tomcat/conf/catalina.properties
            subPath: catalina.properties
        env:
        - name: USE_POD_IP
          value: "true"
        - name: DB_HOST
          value: "teastore-db.teastore.svc.cluster.local"
        envFrom:
          - configMapRef:
              name: teastore-cfg
      volumes:
        - name: tomcat-config
          configMap:
            name: teastore-all
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    injection.smarttuning.ibm.com: "true"
  name: teastore-all
  namespace: teastore
  labels:
    smarttuning: "false"
    run: teastore-all
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    nodePort: 30088
    protocol: TCP
  selector:
    smarttuning: "false"
    run: teastore-all
---

