---
apiVersion: v1
kind: Service
metadata:
  name: acmeair
  labels:
    app: acmeair
spec:
  type: NodePort
  ports:
    # prometheus proxy
    - nodePort: 30099
      port: 9090
      targetPort: 9090
      name: remap
      protocol: TCP
    - port: 9093
      targetPort: 493
      name: https
      protocol: TCP
    - nodePort: 30080
      port: 8888
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: acmeair
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: smarttuning-service
#spec:
#  selector:
#    tuning: "true"
#  ports:
#    - port: 5000
#      targetPort: 5000
#      nodePort: 30050
#      protocol: TCP
#      name: register
#  type: NodePort