apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-tuning
  labels:
    app: "acmeair"
    tuning: "true"
  annotations:
    # https://github.com/stakater/Reloader
    configmap.reloader.stakater.com/reload: "jvm-config-train,acmeair-config-train,proxy-config-train"
spec:
  replicas: 1
  template:
    metadata:
      name: acmeair
      labels:
        app: "acmeair"
        tuning: "true"
    spec:
      containers:
        - name: proxy
          image: smarttuning-proxy
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: proxy-config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - containerPort: 8888
            - containerPort: 9090
        - name: service
          image: liberty-acmeair-k8s
          resources:
            limits:
              cpu: "4"
              memory: "4096Mi"
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              port: 80
              path: /acmeair-webapp/
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: acmeair-config
          volumeMounts:
            - mountPath: /etc/acmeair-config
              name: acmeair-config
            - mountPath: /etc/proxy-config
              name: proxy-config
            - mountPath: /config/jvm.options
              subPath: jvm.options
              name: jvm-config
      volumes:
        - name: acmeair-config
          configMap:
            name: acmeair-config-train
        - name: proxy-config
          configMap:
            name: proxy-config-train
        - name: jvm-config
          configMap:
            name: jvm-config-train
  selector:
    matchLabels:
      app: "acmeair"
      tuning: "true"