apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  TUNING: "TRUE"
  TEST: "TESTING"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: sync
          image: sync
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo 'registering' > /usr/share/pre-start && curl -i \"$REGISTER_ADDR:$REGISTER_PORT/register?name=$POD_NAME&ip=$POD_IP\""]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "echo 'unregistering' > /usr/share/pre-stop && curl -i \"$REGISTER_ADDR:$REGISTER_PORT/unregister?name=$POD_NAME&ip=$POD_IP\""]
          ports:
            - containerPort: 5000
              name: sync
          imagePullPolicy: Never
          env:
            - name: REGISTER_ADDR
              value: 'smarttuning-service.default.svc.cluster.local'
            - name: REGISTER_PORT
              value: '5000'
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGMAP_NAME
              value: 'app-config'
            - name: DEPLOYMENT_NAME
              value: 'app'
        - name: app
          image: alpine-curl
          imagePullPolicy: Never
          command:
            - sh
            - "-c"
            - |
              while :; do
                env
                echo ''
                sleep 2
              done
          envFrom:
            - configMapRef:
                name: app-config
      restartPolicy: Always
      volumes:
        - name: app-config
          configMap:
            name: app-config
  selector:
    matchLabels:
      app: app
