apiVersion: v1
kind: ConfigMap
metadata:
  name: smarttuning-config
data:
  MONGO_ADDR: 'mongo-workload-service.default.svc.cluster.local'
  MONGO_PORT: '27017'
  MONGO_DB: 'smarttuning'
  PROMETHEUS_ADDR: 'prometheus-service.kube-monitoring.svc.cluster.local'
  PROMETHEUS_PORT: '9090'
  NAMESPACE: 'default'
  NAMESPACE_PROD: 'default'
  POD_REGEX: 'acmeair-tuning-.*'
  POD_PROD_REGEX: 'acmeair-tuningprod-.*'
  WAITING_TIME: '900'
  SEARCHSPACE_PATH: '/etc/tuning-search-space/search-space.json'
#  CONFIGMAP_NAME: 'jvm-config-train'
#  CONFIGMAP_PROD_NAME: 'jvm-config-prod'
  CONFIGMAP_NAME: 'acmeair-config-train'
  CONFIGMAP_PROD_NAME: 'acmeair-config-prod'
  MOCK: 'False'
  BAYESIAN: 'True'
  RANDOM_SEED: '31'
  K: '1'
  SAMPLE_SIZE: '0.3334'
  NUMBER_ITERATIONS: '0'
  METRIC_THRESHOLD: '0.0'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarttuning
  labels:
    app: smarttuning
    config: "0"
spec:
  replicas: 1
  template:
    metadata:
      name: smarttuning
      labels:
        app: smarttuning
    spec:
      containers:
        - name: smarttuning
          image: smarttuning
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: smarttuning-config
          volumeMounts:
            - mountPath: /etc/smart-tuning
              name: smarttuning-config
            - mountPath: /etc/tuning-search-space/search-space.json
              name: tuning-search-space
              subPath: search-space.json
      volumes:
        - name: smarttuning-config
          configMap:
            name: smarttuning-config
        - name: tuning-search-space
          configMap:
            name: tuning-search-space
  selector:
    matchLabels:
      app: smarttuning