apiVersion: v1
kind: ConfigMap
metadata:
  name: tuning-config
data:
  TUNING: "TRUE"
  TEST: "TESTING"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuning-search-space
data:
  search-space.json: |
    [
      {
          "key": "TUNING",
          "type": "int",
          "lower": 4,
          "upper": 20,
          "options": null
      },
      {
          "key": "TEST",
          "type": "bool",
          "lower": null,
          "upper": null,
          "options": null
      }
    ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuning
rules:
  - apiGroups: ["*"]
    resources:
      - configmaps
      - deployments
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tuning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tuning
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smarttuning-config
data:
  MONGO_ADDR: 'mongo-workload-service.default.svc.cluster.local'
  MONGO_PORT: '27017'
  MONGO_DB: 'smarttuning'
  PROMETHEUS_ADDR: 'localhost'
  PROMETHEUS_PORT: '9090'
  NAMESPACE: 'default'
  WAITING_TIME: '2'
  CONFIG_PATH: '/etc/smart-tuning'
  SEARCHSPACE_PATH: '/etc/tuning-search-space/search-space.json'
  CONFIGMAP_NAME: 'tuning-config'
  MOCK: 'False'
  NUMBER_ITERATIONS: '3'
  REGISTER_SERVER_PORT: '5000'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smarttuning
  labels:
    app: smarttuning
    config: "0"
spec:
  replicas: 1
  template:
    metadata:
      name: smarttuning
      labels:
        app: smarttuning
    spec:
      containers:
        - name: smarttuning
          image: smarttuning
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: tuning-config
            - configMapRef:
                name: smarttuning-config
          volumeMounts:
            - mountPath: /etc/smart-tuning
              name: smart-tuning-config
            - mountPath: /etc/tuning-search-space/search-space.json
              name: tuning-search-space
              subPath: search-space.json
      terminationGracePeriodSeconds: 1
      restartPolicy: Always
      volumes:
        - name: smart-tuning-config
          configMap:
            name: tuning-config
        - name: tuning-search-space
          configMap:
            name: tuning-search-space
  selector:
    matchLabels:
      app: smarttuning
---
apiVersion: v1
kind: Service
metadata:
  name: smarttuning-service
spec:
  selector:
    app: smarttuning
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
      protocol: TCP
      name: register
  type: NodePort
