apiVersion: "smarttuning.ibm.com/v1alpha2"
kind: SearchSpace
metadata:
  name: daytrader-ss
spec:
  deployment: daytrader-service
  service: daytrader
  namespace: "default"
  manifests:
    - name: daytrader-service
      type: "deployment"
    - name: daytrader-config-app
      type: "configMap"
    - name: daytrader-config-jvm
      type: "configMap"
data:
  - name: daytrader-service
    tunables:
      option:
        - name: "cpu"
          type: "integer"
          values:
            - "2"
            - "4"
            - "8"
            - "16"
        - name: "memory"
          type: "integer"
          values:
            - "512"
            - "1024"
            - "2048"
            - "4096"
            - "8192"
  - name: daytrader-config-app
    tunables:
      number:
        - name: "CONMGR1_MAX_POOL_SIZE"
          lower: 100
          upper: 1000
          step: 100
          real: False
##        - name: "CONMGR1_CONN_PER_THREAD"
##          lower: 1
##          upper: 4
##          real: False
        - name: "CONMGR3_MAX_POOL_SIZE"
          lower: 100
          upper: 1000
          step: 100
          real: False
##        - name: "CONMGR3_CONN_PER_THREAD"
##          lower: 1
##          upper: 4
##          real: False
        - name: "CONMGR4_MAX_POOL_SIZE"
          lower: 100
          upper: 1000
          step: 100
          real: False
##        - name: "CONMGR4_CONN_PER_THREAD"
##          lower: 1
##          upper: 4
##          real: False
        - name: "HTTP_MAX_KEEP_ALIVE_REQUESTS"
          lower: 100
          upper: 1000
          step: 100
          real: False
        - name: "HTTP_PERSIST_TIMEOUT"
          lower: 15
          upper: 45
          step: 5
          real: False
      option:
##        - name: "CONMGR1_PURGE_POLICY"
##          values:
##            - "EntirePool"
##            - "FailingConnectionOnly"
##            - "ValidateAllConnections"
##        - name: "CONMGR3_PURGE_POLICY"
##          values:
##            - "EntirePool"
##            - "FailingConnectionOnly"
##            - "ValidateAllConnections"
##        - name: "CONMGR4_PURGE_POLICY"
##          values:
##            - "EntirePool"
##            - "FailingConnectionOnly"
##            - "ValidateAllConnections"
        - name: "ORDER_PROCESSING_MODE"
##           SYNC:0, ASYNC:1, ASYNC_2P:2
          values:
            - "0"
            - "1"
            - "2"
        - name: "RUNTIME_MODE"
##           FULL_EJB:0, DIRECT:1, SESSION:2
          values:
            - "0"
            - "1"
            - "2"
##        - name: "WEB_INTERFACE"
##           JSP: 0, JSP-IMG: 1
##          values:
##            - "0"
##            - "1"
  - name: daytrader-config-jvm
    filename: "jvm.options"
    tunables:
      boolean:
        - name: "-Xtune:virtualized"
      option:
        - name: "gc"
          values:
            - "-Xgcpolicy:gencon"
            - "-Xgc:concurrentScavenge"
            - "-Xgcpolicy:metronome"
            - "-Xgcpolicy:optavgpause"
            - "-Xgcpolicy:optthruput"
#        - name: "container_support"
#          values:
#            - "-XX:+UseContainerSupport"
#            - "-XX:-UseContainerSupport"
